services:
  postgres-db:
    image: postgres:16.3
    restart: always
    container_name: urls-service
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - urls-service-data:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  urls-service-data:
